=== nockawa/SWGIndustries/src/SWGIndustries/wwwroot/Resources/ServerDefinitions/ServerDefinition.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="http://swgindustries.com/swgserver" elementFormDefault="qualified" targetNamespace="http://swgindustries.com/swgserver" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Server" nillable="true" type="tns:GameServerDefinition" />
  <xs:complexType name="GameServerDefinition">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="Id" type="xs:int" />
      <xs:element minOccurs="1" maxOccurs="1" name="Name" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="ServerWebSiteURL" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="SWGAideResourceFileURL" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="LotCountPerCharacter" type="xs:int" />
      <xs:element minOccurs="1" maxOccurs="1" name="MaxCharacterCountPerAccount" type="xs:int" />
      <xs:element minOccurs="1" maxOccurs="1" name="HarvesterExtractionFactor" type="xs:float" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== nockawa/SWGIndustries/src/SWGIndustries/wwwroot/Resources/ServerDefinitions/SWGRestorationIII.xml
<?xml version="1.0" encoding="utf-8"?>
<Server xmlns="http://swgindustries.com/swgserver"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://swgindustries.com/server ServerDefinition.xsd">
    <Id>1</Id>
    <Name>SWG Restoration III</Name>
    <ServerWebSiteURL>https://swgr.org/home/</ServerWebSiteURL>
    <SWGAideResourceFileURL>https://swgaide.com/pub/exports/currentresources_162.xml.gz</SWGAideResourceFileURL>
    <LotCountPerCharacter>10</LotCountPerCharacter>
    <MaxCharacterCountPerAccount>4</MaxCharacterCountPerAccount>
    <HarvesterExtractionFactor>1.5</HarvesterExtractionFactor>
</Server>
